### ISSUE TITLE
Crashing when casting 'auto' for preset settings

### ISSUE THREAD

**Issue by rromanchuk** [aws-samples/amazon-vod-preset-convert#1]
Looks like it's not able to handle `auto` settings in the preset

```
Please type in a supported ETS region: us-east-1
Preset ID: 1532200621915-3dc1k1
Please type in output a output group type you want to place this ETS preset into, options are file, apple, dash, smooth: file
Traceback (most recent call last):
  File "ets_mediaconvert_preset_v2.py", line 792, in <module>
    emf_VideoDescription = translate_video(ets_preset_payload, s_video)
  File "ets_mediaconvert_preset_v2.py", line 577, in translate_video
    emf_bitrate_temp = int(ets_preset_payload['Preset']['Video']['BitRate'])
ValueError: invalid literal for int() with base 10: 'auto'
``

**Comment by JeremyJohnsonAmazon** [comment]
Thanks for catching this. I've pushed a fix up for this.

**Comment by rromanchuk** [comment]
closing, now fixed. thanks!
